### ISSUE TITLE
when i open the project in eclipse, it can't find com.google.gson

### ISSUE THREAD

**Issue by michielbdejong** [piranna/UnHosted-Java#2]
when i open the project in eclipse, it can't find com.google.gson
do i need to download google gson and link to it?

**Comment by piranna** [comment]
Hi Mich. Yes, gson is a better json-to-java-object parser from Google, i
used it to convert automagically the stored data in objects. You can get it
from Google Code, but i don't remember the url.

Just one note, at this moment the Java port doesn't work and until i finish
the exams the next 4th July i will not be able to improve it too much... the
good news is that at my new job i'm working with Android :-)

Enviado desde mi nuevo Galaxy Tab ;-)
El 07/06/2011 14:48, "michiel-unhosted" <
reply@reply.github.com>
escribi:

**Comment by michielbdejong** [comment]
great! i will make the code work this week, because next week I'm
using it for this:
http://swdc-central.com/androidonly2011malmo/workshop/

On Tue, Jun 7, 2011 at 2:53 PM, piranna
reply@reply.github.com
wrote:

**Comment by piranna** [comment]
lol :-P Ok, the general structure is done, and as you can see, it's portable
between Android and desktop, it show a popup if not logeg and only keep to
insert correct code :-) good luck! :-)

Enviado desde mi nuevo Galaxy Tab ;-)
El 07/06/2011 15:02, "michiel-unhosted" <
reply@reply.github.com>
escribi:

**Comment by piranna** [comment]
Hi Mich, i think this link will be useful, i was looking for something
similar to this: how to create and configure an Android library
project with Eclipse. With that, unhosted would be just a simple
pluggable Android library for Android apps or Java package for desktop
apps (since the login window interface is different at both systems...
althought we develop a pure, no interface Java package and later every
app develop their own custom login window...).

http://developer.android.com/guide/developing/projects/projects-eclipse.html

2011/6/7 piranna@gmail.com piranna@gmail.com:

> lol :-P Ok, the general structure is done, and as you can see, it's portable
> between Android and desktop, it show a popup if not logeg and only keep to
> insert correct code :-) good luck! :-)
> 
> Enviado desde mi nuevo Galaxy Tab ;-)
> 
> El 07/06/2011 15:02, "michiel-unhosted"
> reply@reply.github.com
> escribió:
> 
> > great! i will make the code work this week, because next week I'm
> > using it for this:
> > http://swdc-central.com/androidonly2011malmo/workshop/
> > 
> > On Tue, Jun 7, 2011 at 2:53 PM, piranna
> > reply@reply.github.com
> > wrote:
> > 
> > > Hi Mich. Yes, gson is a better json-to-java-object parser from Google, i
> > > used it to convert automagically the stored data in objects. You can get
> > > it
> > > from Google Code, but i don't remember the url.
> > > 
> > > Just one note, at this moment the Java port doesn't work and until i
> > > finish
> > > the exams the next 4th July i will not be able to improve it too much...
> > > the
> > > good news is that at my new job i'm working with Android :-)
> > > 
> > > Enviado desde mi nuevo Galaxy Tab ;-)
> > > El 07/06/2011 14:48, "michiel-unhosted" <
> > > reply@reply.github.com>
> > > escribi:
> > > 
> > > > when i open the project in eclipse, it can't find com.google.gson
> > > > do i need to download google gson and link to it?
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/piranna/UnHosted-Java/issues/2
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/piranna/UnHosted-Java/issues/2#comment_1315504
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/piranna/UnHosted-Java/issues/2#comment_1315545

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux
